
---
- name: create nginx includes dir
  file:
    state: directory
    path: /etc/nginx/includes/
    mode: og+wr
    owner: root
    group: root

- name: 1 NGINX fuseki config
  template:
    src: nginx_fuseki.j2
    dest: '/etc/nginx/{{ nginx_fuseki_conf }}'
    mode: og+wr
    owner: root
    group: root

- name: remove comments from NGINX site default
  lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: '#\s*?.*$'
    state: absent

- name: insert fuseki conf to NGINX site default
  lineinfile:
    path: /etc/nginx/sites-available/default
    insertafter: 'server_name _;'
    line: '        include {{ nginx_fuseki_conf }};'
    mode: og+wr
    owner: root
    group: root

- name: 3 enable NGINX default config
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart_webserver

- name: print location
  debug:
    msg: "Fuseki at {{ vm_url }}"

