- name: start_fuseki_service
  systemd:
    name: fuseki.service
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart_fuseki_service
  systemd:
    name: fuseki.service
    state: restarted

- name: restart_webserver
  service:
    name: nginx
    state: restarted

- name: reload_systemd
  command: systemctl daemon-reload
