---

- name: Create fuseki config dir
  file:
    path: '{{ fuseki_config_dir }}'
    state: directory
    owner: root
    group: root


- name: Download Jena & Fuseki
  unarchive:
    src: '{{ item.binary }}'
    dest: '{{ item.dir }}'
    remote_src: yes
  loop:
    - { binary: '{{ jena_binary }}', dir: '{{ src_dir }}' }
    - { binary: '{{ fuseki_binary }}', dir: '{{ src_dir }}' }


- name: Configuration files
  template:
    src: '{{ item }}'
    dest: '{{ fuseki_config_dir }}/{{ item }}'
    owner: root
    group: root
  loop:
    - shiro.ini
    - config.ttl

- name: Create and start fuseki.service
  template:
    src: fuseki.service
    dest: '{{ fuseki_service_file }}'
    owner: root
    group: root
  notify: start_fuseki_service

# prepare loading files to tbd2
- name: stop fuseki service
  systemd:
    name: fuseki.service
    state: stopped

- name: create fuseki configdir
  file:
    path: '{{ fuseki_config_dir }}/configuration/'
    state: directory
    owner: root
    group: root
    mode: 'a+rw'

# load rxno to tbd2
- name: Download rxno.owl
  get_url:
    url: https://raw.githubusercontent.com/rsc-ontologies/rxno/master/rxno.owl
    dest: '{{ src_dir }}/rxno.owl'
    mode: "a+rw"

- name: load rxno to tdb2
  command:
    cmd: '{{ jena_src_dir }}/bin/tdb2.tdbloader --loc={{ fuseki_config_dir }}/databases/rxno {{ src_dir }}/rxno.owl'
  # notify: start_fuseki_service

- name: copy fuseki rxno dataset config
  copy:
    src: rxno_config.ttl
    dest: '{{ fuseki_config_dir }}/configuration/rxno.ttl'

# load ckan1368
- name: Download catalog.ttl
  get_url:
    url: https://service.tib.eu/sfb1368/ckan/catalog.ttl
    dest: '{{ src_dir }}/catalog.ttl'
    mode: "a+rw"

- name: load catalog to tdb2
  command:
    cmd: '{{ jena_src_dir }}/bin/tdb2.tdbloader --loc={{ fuseki_config_dir }}/databases/ckan1368 {{ src_dir }}/catalog.ttl'
  # notify: start_fuseki_service

- name: copy fuseki ckan1368 dataset config
  copy:
    src: ckan1368.ttl
    dest: '{{ fuseki_config_dir }}/configuration/ckan1368.ttl'

# load test
- name: load catalog to tdb2
  command:
    cmd: '{{ jena_src_dir }}/bin/tdb2.tdbloader --loc={{ fuseki_config_dir }}/databases/test {{ src_dir }}/test.ttl'

- name: copy fuseki test dataset config
  copy:
    src: test_config.ttl
    dest: '{{ fuseki_config_dir }}/configuration/test.ttl'


- name: start fuseki
  systemd:
    name: fuseki.service
    state: started
