---

- name: Create fuseki config dir
  file: 
    path: '{{ fuseki_config_dir }}'
    state: directory
    owner: root
    group: root


- name: Download Jena & Fuseki
  unarchive:
    src: '{{ item.binary }}'
    dest: '{{ item.dir }}'
    remote_src: yes
  loop:
    - { binary: '{{ jena_binary }}', dir: '{{ src_dir }}' }
    - { binary: '{{ fuseki_binary }}', dir: '{{ src_dir }}' }


- name: Configuration files
  template:
    src: '{{ item }}'
    dest: '{{ fuseki_config_dir }}/{{ item }}'
    owner: root
    group: root
  loop:
    - shiro.ini
    - config.ttl

- name: Create and start fuseki.service
  template:
    src: fuseki.service
    dest: '{{ fuseki_service_file }}'
    owner: root
    group: root
  notify: start_fuseki_service


# load data to tdb2
- name: stop fuseki service
  systemd:
    name: fuseki.service
    state: stop

- name: Download rxno.owl
  get_url:
    url: https://raw.githubusercontent.com/rsc-ontologies/rxno/master/rxno.owl
    dest: '{{ src_dir }}/rxno.owl'
    mode: "a+rw"

- name: load rxno to tdb2
  command:
    cmd: '{{ fuseki_src_dir }}/bin/tdb2.tdbloader --loc={{ fuseki_config_dir }}/databases/rxno {{ src_dir }}/rxno.owl' 
  notify: start_fuseki_service


- name: create rxno dataset
  command:
    cmd: '{{ fuseki_src_dir }}/fuseki-server  --tdb2 --loc={{ fuseki_config_dir }}/databases/rxno /rxno' 
